### SERVICE DATABASE
apiVersion: v1
kind: Service
metadata:
  name: dio-db
spec:
  selector:
    app: dio-db
  ports:
    - port: 3306
  clusterIP: None


---
### SERVICE BACKEND
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend-php
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer


